# Generated by Django 5.1.4 on 2025-01-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquote',
            managers=[
            ],
        ),
    ]
