# Generated by Django 5.1.4 on 2025-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_stockquote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquote',
            name='raw_timestamp',
            field=models.CharField(blank=True, help_text='Non transformed timestamp string or int or float', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stockquote',
            name='volume_weighted_average',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
